CREATE DATABASE HROADS;
GO

USE HROADS;
GO

CREATE TABLE PERSONAGEM (
	idPersonagem SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomePersonagem VARCHAR(40) NOT NULL,
	dataAtualizacao VARCHAR (15) NOT NULL,
	dataCriacao DATE NOT NULL

);
GO

CREATE TABLE CLASSE(
	idClasse SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPersonagem SMALLINT FOREIGN KEY REFERENCES PERSONAGEM(idPersonagem),
	nomeClasse VARCHAR(20) NOT NULL,
	capMaxVida VARCHAR(10) NOT NULL,
	capMaxMana VARCHAR(10) NOT NULL

);
GO

CREATE TABLE HABILIDADE(
	idHabilidade SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeHabilidade VARCHAR(20) NOT NULL

);
GO

CREATE TABLE CLASSE_HABILIDADE (
	idClasseHabilidade SMALLINT PRIMARY KEY IDENTITY (1,1),
	idClasse SMALLINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade)

);
GO

CREATE TABLE TIPO_HABILIDADE (
	idTipoHabilidade SMALLINT PRIMARY KEY IDENTITY (1,1),
	idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
	tipoHabilidade VARCHAR(20) NOT NULL
);
GO